### PR TITLE
Add libwebp so pillow builds with webp support

### PR DESCRIPTION
**Pull request by cwhits**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-mylar3/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Without webp, any webp comics inside of Mylar fail to load when you hit the info button. Running the following python code will return `False` because webp wasn't on the system when pillow was installed via pip.
```python
from PIL import features
print(features.check_module('webp'))
```

Inside of Mylar, you'll see a warning similar to the following:
```
WARNING    [WARNING] Unable to resize existing image: cannot identify image file <_io.BytesIO object at 0x7f2fd9bfaf40>
```

This PR adds libwebp-dev to the build phase and libwebp-tools to the runtime phase so the libcwebp libraries are available during when PIP installs Pillow (used for displaying images inside of Mylar), thus enabling webp as a Pillow feature, and so cwebp is available in the container for ComicTagger.

## Benefits of this PR and context:

Allows Mylar to properly display covers for webp comics. 

## How Has This Been Tested?

I modified and built the container, `docker exec -it mylar bash` > `python3` and ran 
```python
from PIL import features
print(features.check_module('webp'))
``` 
and verified that it returned true. I then loaded the front-end UI and checked that the info button would work on a comic that contained webp images.

## Source / References:

Worked with evilhero over on the Mylar discord to figure out this was related to Pillow being installed without the webp libraries.

### CODE REVIEW

**Comment by aptalca** [comment]
Thanks for the PR. Please add a changelog entry into readme-vars.yml and submit a similar PR to the nightly branch as well. Thanks

**Comment by cwhits** [comment]
@aptalca sorry, forgive my ignorance, but to verify:
-  add the readme-vars.yml changes to this PR
-  dupe the whole thing (including readme-vars.yml) against the nightly branch?
or am I re-submitting the whole thing _against_ the nightly branch?

**Comment by aptalca** [comment]
readme-vars-yml would update the readme of this branch and would complete this PR.
Then, please submit a separate PR with the same changes (added packages) to the nightly branch because that branch publishes the `nightly` tag for the image, whereas the master branch here publishes the `latest` branch.

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
Looks great, thanks!

**Pull request merged**
